import { StyleSheet } from 'react-native';
import colors from './colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray.light,
    padding: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    fontSize: 16,
    color: 'red',
    textAlign: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.primary,
    textAlign: 'center',
    marginBottom: 20,
  },
  chart: {
    height: 200,
    width: 200,
    alignSelf: 'center',
    marginBottom: 20,
  },
  budgetDetails: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.gray.dark,
    textAlign: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.gray.dark,
    marginBottom: 10,
  },
  budgetItem: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  budgetName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.gray.dark,
  },
  budgetAmount: {
    fontSize: 14,
    color: colors.primary,
    marginTop: 5,
  },
  transactionItem: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  transactionDescription: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.gray.dark,
  },
  transactionDetail: {
    fontSize: 14,
    color: colors.primary,
    marginTop: 5,
  },
  transactionDate: {
    fontSize: 12,
    color: colors.gray.medium,
    marginTop: 2,
  },
  addButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: colors.primary,
    borderRadius: 30,
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  addButtonText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.white,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.white,
    marginBottom: 10,
  },
  modalInput: {
    width: '80%',
    padding: 10,
    backgroundColor: colors.white,
    borderRadius: 8,
    marginBottom: 10,
    fontSize: 16,
    color: colors.gray.dark,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
    marginTop: 10,
  },
  modalButton: {
    flex: 1,
    marginHorizontal: 5,
  },
});
